INSERT INTO MOOD VALUES (1 , 'mood1');
INSERT INTO MOOD VALUES (2 , 'mood2');

INSERT INTO GENRE VALUES (1, 'genre1');
INSERT INTO GENRE VALUES (2, 'genre2');

INSERT INTO SONG_IMAGE_PATH VALUES (1, '1');
INSERT INTO SONG_IMAGE_PATH VALUES (2, '2');

INSERT INTO SONG_IMAGE VALUES (SEQ_SONG_IMAGE_NO.NEXTVAL, 1,'1');
INSERT INTO SONG_IMAGE VALUES (SEQ_SONG_IMAGE_NO.NEXTVAL, 2,'2');

INSERT INTO SONG_PATH VALUES (1, '1');
INSERT INTO SONG_PATH VALUES (2, '2');

INSERT INTO SONG_FILE VALUES (SEQ_SONG_FILE_NO.NEXTVAL, 1, 'CHANGENAME1', 'ORIGINNAME1' );
INSERT INTO SONG_FILE VALUES (SEQ_SONG_FILE_NO.NEXTVAL, 2, 'CHANGENAME2', 'ORIGINNAME2' );

INSERT INTO PROFILE_IMAGE VALUES (SEQ_MEMBER_PROFILE_IMAGE_NO.NEXTVAL, '1');
INSERT INTO PROFILE_IMAGE VALUES (SEQ_MEMBER_PROFILE_IMAGE_NO.NEXTVAL, '2');

INSERT INTO MEMBER_BANNER VALUES (0, 'DEFAUL IMAGE' );
INSERT INTO MEMBER_BANNER VALUES (SEQ_MEMBER_BANNER_NO.NEXTVAL, 'banner 1' );
INSERT INTO MEMBER_BANNER VALUES (SEQ_MEMBER_BANNER_NO.NEXTVAL, 'banner 2' );

INSERT INTO MEMBER_GRADE VALUES (0, '관리자');
INSERT INTO MEMBER_GRADE VALUES (1, '일반사용자');

INSERT INTO MEMBER VALUES (SEQ_MEMBER_NO.NEXTVAL, 1, DEFAULT, DEFAULT, 'NICKNAME1', NULL, NULL, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO MEMBER VALUES (SEQ_MEMBER_NO.NEXTVAL, 2, DEFAULT, DEFAULT, 'NICKNAME2', NULL, NULL, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO SONG VALUES (
    SEQ_SONG_NO.NEXTVAL, 1, 1, 1, 1, 1, DEFAULT, 'TITLE 1', 'LICENSE 1', 'DETAIL 1',  DEFAULT, DEFAULT, DEFAULT
);

INSERT INTO SONG VALUES (
    SEQ_SONG_NO.NEXTVAL, 2, 2, 2, 2, 2, DEFAULT, 'TITLE 2', 'LICENSE 2', 'DETAIL 2',  DEFAULT, DEFAULT, DEFAULT
);

INSERT INTO SONG VALUES (
    SEQ_SONG_NO.NEXTVAL, 2, 2, 2, 2, 2, DEFAULT, 'TITLE 3', 'LICENSE 3', 'DETAIL 3',  DEFAULT, DEFAULT, DEFAULT
);

INSERT INTO SONG VALUES (
    SEQ_SONG_NO.NEXTVAL, 2, 2, 2, 2, 2, DEFAULT, 'TITLE 4', 'LICENSE 4', 'DETAIL 4',  DEFAULT, DEFAULT, DEFAULT
);

INSERT INTO SONG VALUES (
    SEQ_SONG_NO.NEXTVAL, 2, 2, 2, 2, 2, DEFAULT, 'TITLE 5', 'LICENSE 5', 'DETAIL 5',  DEFAULT, DEFAULT, DEFAULT
);

INSERT INTO SONG VALUES (
    SEQ_SONG_NO.NEXTVAL, 1, 1, 1, 1, 1, DEFAULT, 'TITLE 6', NULL, 'DETAIL 6',  DEFAULT, DEFAULT, DEFAULT
);

INSERT INTO SONG VALUES (
    SEQ_SONG_NO.NEXTVAL, 1, 2, 1, 2, 2, DEFAULT, 'TITLE 7', 'LICENSE 7', NULL,  DEFAULT, DEFAULT, DEFAULT
);

INSERT INTO SONG VALUES (
    SEQ_SONG_NO.NEXTVAL, 2, 1, 1, 1, 2, DEFAULT, 'TITLE 8', 'LICENSE 8', NULL,  DEFAULT, DEFAULT, DEFAULT
);

INSERT INTO SONG VALUES (
    SEQ_SONG_NO.NEXTVAL, 1, 1, 1, 1, 2, DEFAULT, 'TITLE 9', 'LICENSE 9', NULL,  DEFAULT, DEFAULT, DEFAULT
);

INSERT INTO SONG VALUES (
    SEQ_SONG_NO.NEXTVAL, 2, 2, 2, 2, 2, DEFAULT, 'TITLE 10', 'LICENSE 10', 'DETAIL 10',  DEFAULT, DEFAULT, DEFAULT
);

INSERT INTO SONG VALUES (
    SEQ_SONG_NO.NEXTVAL, 2, 2, 2, 2, 2, DEFAULT, 'TITLE 11', 'LICENSE 11', 'DETAIL 11',  DEFAULT, DEFAULT, DEFAULT
);

INSERT INTO SONG VALUES (
    SEQ_SONG_NO.NEXTVAL, 2, 2, 2, 2, 2, DEFAULT, 'TITLE 12', 'LICENSE 12', 'DETAIL 12',  DEFAULT, DEFAULT, DEFAULT
);

INSERT INTO SONG VALUES (
    SEQ_SONG_NO.NEXTVAL, 2, 2, 2, 2, 2, DEFAULT, 'TITLE 13', 'LICENSE 13', 'DETAIL 13',  DEFAULT, DEFAULT, DEFAULT
);

INSERT INTO SONG VALUES (
    SEQ_SONG_NO.NEXTVAL, 2, 2, 2, 2, 2, DEFAULT, 'TITLE 14', 'LICENSE 14', 'DETAIL 14',  DEFAULT, DEFAULT, DEFAULT
);

INSERT INTO SONG VALUES (
    SEQ_SONG_NO.NEXTVAL, 2, 2, 2, 2, 2, DEFAULT, 'TITLE 15', 'LICENSE 15', 'DETAIL 15',  DEFAULT, DEFAULT, DEFAULT
);

INSERT INTO SONG VALUES (
    SEQ_SONG_NO.NEXTVAL, 1, 1, 2, 2, 1, DEFAULT, 'TITLE 16', 'LICENSE 16', 'DETAIL 16',  DEFAULT, DEFAULT, DEFAULT
);

INSERT INTO SONG VALUES (
    SEQ_SONG_NO.NEXTVAL, 2, 2, 2, 2, 2, DEFAULT, 'TITLE 17', 'LICENSE 17', 'DETAIL 17',  DEFAULT, DEFAULT, DEFAULT
);

INSERT INTO SONG VALUES (
    SEQ_SONG_NO.NEXTVAL, 2, 1, 1, 1, 2, DEFAULT, 'TITLE 18', 'LICENSE 18', 'DETAIL 18',  DEFAULT, DEFAULT, DEFAULT
);

INSERT INTO SONG VALUES (
    SEQ_SONG_NO.NEXTVAL, 2, 2, 2, 2, 2, DEFAULT, 'TITLE 19', NULL, 'DETAIL 19',  DEFAULT, DEFAULT, DEFAULT
);

INSERT INTO SONG VALUES (
    SEQ_SONG_NO.NEXTVAL, 2, 2, 2, 2, 2, DEFAULT, 'TITLE 20', 'LICENSE 20', 'DETAIL 20',  DEFAULT, DEFAULT, DEFAULT
);

INSERT INTO SONG VALUES (
    SEQ_SONG_NO.NEXTVAL, 1, 1, 1, 2, 2, DEFAULT, 'TITLE 21', 'LICENSE 21', 'DETAIL 21',  DEFAULT, DEFAULT, DEFAULT
);

commit;
